// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrHqwUlxL5Z47Kjfr2U8NoS7CVXHdcyWk',
    appId: '1:528687970124:web:0c0c8d60d66200fb01c1e9',
    messagingSenderId: '528687970124',
    projectId: 'whisker-works',
    authDomain: 'whisker-works.firebaseapp.com',
    storageBucket: 'whisker-works.firebasestorage.app',
    measurementId: 'G-GMK530X39D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDv-gKv0bukJ8Ng6LMr6H5mbANzZAWSr0',
    appId: '1:528687970124:android:a6aee6a14fdaba0101c1e9',
    messagingSenderId: '528687970124',
    projectId: 'whisker-works',
    storageBucket: 'whisker-works.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoYfEFtV93AGQVasCpunwt4gUM7Jz0F90',
    appId: '1:528687970124:ios:a5d1c1e182a33fdf01c1e9',
    messagingSenderId: '528687970124',
    projectId: 'whisker-works',
    storageBucket: 'whisker-works.firebasestorage.app',
    iosBundleId: 'com.example.mouseColonyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoYfEFtV93AGQVasCpunwt4gUM7Jz0F90',
    appId: '1:528687970124:ios:351e01edfda458b001c1e9',
    messagingSenderId: '528687970124',
    projectId: 'whisker-works',
    storageBucket: 'whisker-works.firebasestorage.app',
    iosBundleId: 'com.whiskerworks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrHqwUlxL5Z47Kjfr2U8NoS7CVXHdcyWk',
    appId: '1:528687970124:web:130e1889223d0b2e01c1e9',
    messagingSenderId: '528687970124',
    projectId: 'whisker-works',
    authDomain: 'whisker-works.firebaseapp.com',
    storageBucket: 'whisker-works.firebasestorage.app',
    measurementId: 'G-3Z8J2QCN8G',
  );
}
